# Importing Libraries

In [2]:
# Import Libraries
import pandas as pd
import numpy as np
import os

# Importing Data

In [3]:
# Create Path
path= r'C:\Users\jenni\OneDrive\Documenten\Data Analyst Program\Data Analytics Immersion\Achievement 4\02-2024 Instacart Basket Analysis'

In [4]:
# Importing Merged Dataframe
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_agg.pkl'))

# Task

In [5]:
# Mean of Order Number by Department ID
ords_prods_merge.groupby('department_id').agg({'order_number' : ['mean']}).round(0)

              order_number
                      mean
department_id
1                     15.0
2                     17.0
3                     17.0
4                     18.0
5                     15.0
6                     16.0
7                     17.0
8                     15.0
9                     16.0
10                    20.0
11                    16.0
12                    16.0
13                    17.0
14                    17.0
15                    16.0
16                    18.0
17                    16.0
18                    19.0
19                    17.0
20                    16.0
21                    23.0

In [6]:
# Preparing for Sorting
department_order_mean = ords_prods_merge.groupby('department_id').agg({'order_number': 'mean'})

In [7]:
# Sorting
department_order_mean_sorted = department_order_mean.sort_values(by=('order_number'), ascending = False).round(0)

In [8]:
department_order_mean_sorted

               order_number
department_id
21                     23.0
10                     20.0
18                     19.0
4                      18.0
16                     18.0
2                      17.0
7                      17.0
19                     17.0
3                      17.0
14                     17.0
13                     17.0
20                     16.0
6                      16.0
11                     16.0
15                     16.0
9                      16.0
12                     16.0
17                     16.0
1                      15.0
8                      15.0
5                      15.0

### Differences Subset and Entire Dataframe
For starters, the entire dataframe has more rows/departments than its subset counterpart. There are quite a few missing in the subset while the entire dataframe seems to be complete.
Beyond that, the means are different for the departments that are in both dataframes

### Creating Loyalty Flag

In [10]:
# Defining Max Order
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform('max')

In [11]:
# Ensuring 100 rows can be displayed
pd.options.display.max_rows = None

In [12]:
# Checking the new Column
ords_prods_merge.head(100)

,Unnamed: 0.1_x,Unnamed: 0_x,order_id,user_id,order_number,orders_day_of_week,orders_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,...,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,hour_of_day_counts,max_order,loyalty_flag,loyalty
0,0,0,2539329,1,1,2,8,11.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,218769.0,10,New customer,New customer
1,1,1,2398795,1,2,3,7,15.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Least busy,Fewest orders,115700.0,10,New customer,New customer
2,2,2,473747,1,3,3,12,21.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,69375.0,10,New customer,New customer
3,3,3,2254736,1,4,4,7,29.0,196,1,...,9.0,both,Mid-range product,Least busy,Least busy,Fewest orders,51281.0,10,New customer,New customer
4,4,4,431534,1,5,4,15,28.0,196,1,...,9.0,both,Mid-range product,Least busy,Least busy,Most orders,53242.0,10,New customer,New customer
5,5,5,3367565,1,6,2,7,19.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Fewest orders,87961.0,10,New customer,New customer
6,6,6,550135,1,7,1,9,20.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Average orders,290493.0,10,New customer,New customer
7,7,7,3108588,1,8,1,14,14.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,891054.0,10,New customer,New customer
8,8,8,2295261,1,9,1,16,0.0,196,4,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,1718118.0,10,New customer,New customer
9,9,9,2550362,1,10,4,8,30.0,196,1,...,9.0,both,Mid-range product,Least busy,Least busy,Average orders,2454203.0,10,New customer,New customer
10,144,144,2968173,15,15,1,9,7.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Average orders,2761760.0,22,Regular customer,Regular customer
11,146,146,1870022,15,17,2,16,8.0,196,6,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,2736140.0,22,Regular customer,Regular customer
12,147,147,1911383,15,18,2,11,7.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,2618532.0,22,Regular customer,Regular customer
13,150,150,2715276,15,21,1,9,7.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Average orders,2660954.0,22,Regular customer,Regular customer
14,151,151,487368,15,22,1,10,14.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,2689136.0,22,Regular customer,Regular customer
15,209,209,2293453,19,2,5,14,6.0,196,3,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,2662144.0,9,New customer,Regular customer
16,212,212,1973799,19,5,6,12,8.0,196,15,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,2535202.0,9,New customer,Regular customer
17,214,214,532817,19,7,4,17,6.0,196,1,...,9.0,both,Mid-range product,Least busy,Least busy,Average orders,2087654.0,9,New customer,Regular customer
18,232,232,1573906,21,10,3,10,6.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,1636502.0,33,Regular customer,Regular customer
19,458,458,1593000,31,10,3,8,7.0,196,17,...,9.0,both,Mid-range product,Regularly busy,Least busy,Average orders,1258305.0,20,Regular customer,Regular customer
20,465,465,2231262,31,17,3,11,8.0,196,14,...,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,976156.0,20,Regular customer,Regular customer
21,617,617,2580647,43,6,4,16,4.0,196,9,...,9.0,both,Mid-range product,Least busy,Least busy,Most orders,795637.0,11,Regular customer,nan
22,620,620,2187180,43,9,4,12,3.0,196,1,...,9.0,both,Mid-range product,Least busy,Least busy,Most orders,634225.0,11,Regular customer,nan
23,751,751,2497897,52,1,1,9,11.0,196,4,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Average orders,402316.0,27,Regular customer,nan
24,752,752,1318871,52,2,1,10,7.0,196,5,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,NaN,27,Regular customer,nan
25,753,753,1261384,52,3,1,10,7.0,196,3,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,NaN,27,Regular customer,nan
26,755,755,580568,52,5,2,10,8.0,196,6,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,27,Regular customer,nan
27,757,757,2428073,52,7,2,7,8.0,196,5,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Fewest orders,NaN,27,Regular customer,nan
28,759,759,342306,52,9,1,11,7.0,196,5,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,NaN,27,Regular customer,nan
29,760,760,1520353,52,10,2,10,8.0,196,4,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,27,Regular customer,nan
30,761,761,2542086,52,11,2,9,7.0,196,3,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,NaN,27,Regular customer,nan
31,762,762,944694,52,12,1,16,6.0,196,7,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,NaN,27,Regular customer,nan
32,765,765,1268191,52,15,2,11,8.0,196,3,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,27,Regular customer,nan
33,767,767,1122089,52,17,2,10,6.0,196,4,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,27,Regular customer,nan
34,768,768,1498922,52,18,2,10,14.0,196,6,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,27,Regular customer,nan
35,769,769,180919,52,19,3,8,8.0,196,4,...,9.0,both,Mid-range product,Regularly busy,Least busy,Average orders,NaN,27,Regular customer,nan
36,771,771,2695875,52,21,5,10,30.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,27,Regular customer,nan
37,1022,1022,3205960,67,1,3,11,11.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,NaN,24,Regular customer,nan
38,1023,1023,970922,67,2,1,15,5.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,NaN,24,Regular customer,nan
39,1024,1024,596585,67,3,1,13,7.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,NaN,24,Regular customer,nan
40,1025,1025,2037087,67,4,2,9,8.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,NaN,24,Regular customer,nan
41,1026,1026,2474111,67,5,3,14,8.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,NaN,24,Regular customer,nan
42,1027,1027,1568481,67,6,3,12,7.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,NaN,24,Regular customer,nan
43,1029,1029,2048527,67,8,2,11,7.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,24,Regular customer,nan
44,1030,1030,2389031,67,9,2,14,7.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,24,Regular customer,nan
45,1031,1031,2378562,67,10,1,10,6.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,NaN,24,Regular customer,nan
46,1032,1032,1515698,67,11,1,11,7.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,NaN,24,Regular customer,nan
47,1033,1033,1928050,67,12,2,12,8.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,24,Regular customer,nan
48,1034,1034,1949274,67,13,1,10,6.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,NaN,24,Regular customer,nan
49,1035,1035,551869,67,14,1,9,7.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Average orders,NaN,24,Regular customer,nan
50,1037,1037,768572,67,16,4,10,9.0,196,1,...,9.0,both,Mid-range product,Least busy,Least busy,Most orders,NaN,24,Regular customer,nan
51,1039,1039,150528,67,18,5,16,4.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,24,Regular customer,nan
52,1040,1040,29758,67,19,0,14,9.0,196,2,...,9.0,both,Mid-range product,Busiest day,Busiest day,Most orders,NaN,24,Regular customer,nan
53,1042,1042,1558976,67,21,1,9,5.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Average orders,NaN,24,Regular customer,nan
54,1043,1043,863974,67,22,1,11,14.0,196,3,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,NaN,24,Regular customer,nan
55,1044,1044,2308399,67,23,1,14,14.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,NaN,24,Regular customer,nan
56,1202,1202,2759128,81,3,1,9,14.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Average orders,NaN,7,New customer,nan
57,1204,1204,1812985,81,5,2,20,30.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,NaN,7,New customer,nan
58,1208,1208,1889835,82,1,3,15,11.0,196,6,...,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,NaN,19,Regular customer,nan
59,1210,1210,499460,82,3,5,10,5.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,19,Regular customer,nan
60,1211,1211,2728456,82,4,0,11,16.0,196,1,...,9.0,both,Mid-range product,Busiest day,Busiest day,Most orders,NaN,19,Regular customer,nan
61,1213,1213,2653743,82,6,4,9,13.0,196,5,...,9.0,both,Mid-range product,Least busy,Least busy,Average orders,NaN,19,Regular customer,nan
62,1216,1216,1358880,82,9,1,10,30.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,NaN,19,Regular customer,nan
63,1217,1217,343588,82,10,2,11,1.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,19,Regular customer,nan
64,1222,1222,3034663,82,15,2,11,12.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,19,Regular customer,nan
65,1225,1225,147262,82,18,1,13,7.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,NaN,19,Regular customer,nan
66,1226,1226,3144004,82,19,2,15,8.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,19,Regular customer,nan
67,1480,1480,2126069,98,3,0,9,25.0,196,7,...,9.0,both,Mid-range product,Busiest day,Busiest day,Average orders,NaN,14,Regular customer,nan
68,1484,1484,2210120,98,7,5,14,5.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,14,Regular customer,nan
69,1486,1486,681011,98,9,3,9,30.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Least busy,Average orders,NaN,14,Regular customer,nan
70,1488,1488,2846344,98,11,4,13,15.0,196,2,...,9.0,both,Mid-range product,Least busy,Least busy,Most orders,NaN,14,Regular customer,nan
71,1489,1489,747431,98,12,6,13,30.0,196,4,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,14,Regular customer,nan
72,1490,1490,2383054,98,13,4,11,30.0,196,1,...,9.0,both,Mid-range product,Least busy,Least busy,Most orders,NaN,14,Regular customer,nan
73,1491,1491,1993729,98,14,5,8,8.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,NaN,14,Regular customer,nan
74,1608,1608,1403849,109,3,3,17,9.0,196,5,...,9.0,both,Mid-range product,Regularly busy,Least busy,Average orders,NaN,6,New customer,nan
75,1744,1744,520620,120,1,3,11,11.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,NaN,3,New customer,nan
76,1746,1746,3273029,120,3,2,8,19.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,NaN,3,New customer,nan
77,2781,2781,1861943,185,2,1,12,25.0,196,10,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,NaN,6,New customer,nan
78,2891,2891,2040988,195,1,1,14,11.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,NaN,58,Loyal customer,nan
79,2898,2898,1680569,195,8,1,9,4.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Average orders,NaN,58,Loyal customer,nan
80,2909,2909,276171,195,19,5,11,3.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,58,Loyal customer,nan
81,2912,2912,2744976,195,22,5,10,7.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,58,Loyal customer,nan
82,2915,2915,2781919,195,25,1,14,4.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,NaN,58,Loyal customer,nan
83,2921,2921,1738718,195,31,2,8,4.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,NaN,58,Loyal customer,nan
84,2924,2924,3058369,195,34,3,10,6.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,NaN,58,Loyal customer,nan
85,2927,2927,1485596,195,37,2,15,0.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,58,Loyal customer,nan
86,2930,2930,417035,195,40,3,16,2.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,NaN,58,Loyal customer,nan
87,2937,2937,1615297,195,47,5,10,2.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,58,Loyal customer,nan
88,2942,2942,1765587,195,52,3,12,2.0,196,3,...,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,NaN,58,Loyal customer,nan
89,2947,2947,745908,195,57,4,11,3.0,196,3,...,9.0,both,Mid-range product,Least busy,Least busy,Most orders,NaN,58,Loyal customer,nan
90,3451,3451,2505656,222,17,2,12,1.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,70,Loyal customer,nan
91,3472,3472,3268370,222,38,5,15,1.0,196,6,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,70,Loyal customer,nan
92,4667,4667,2016711,290,9,5,19,6.0,196,8,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,NaN,51,Loyal customer,nan
93,4686,4686,2706088,290,28,6,10,7.0,196,16,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,51,Loyal customer,nan
94,5551,5551,1952286,331,6,5,16,30.0,196,8,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,8,New customer,nan
95,5895,5895,3226575,360,1,5,12,11.0,196,1,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,NaN,3,New customer,nan
96,6137,6137,1469869,377,3,5,17,3.0,196,9,...,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,NaN,3,New customer,nan
97,6259,6259,1927023,387,2,4,10,22.0,196,3,...,9.0,both,Mid-range product,Least busy,Least busy,Most orders,NaN,8,New customer,nan
98,6740,6740,858092,420,4,1,19,30.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Busiest day,Average orders,NaN,22,Regular customer,nan
99,6741,6741,119314,420,5,3,19,16.0,196,2,...,9.0,both,Mid-range product,Regularly busy,Least busy,Average orders,NaN,22,Regular customer,nan

#### Creating Loyalty Flags

In [13]:
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [14]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [15]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [16]:
# Checking the New Flags
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [17]:
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             2
2         1      New customer             3
3         1      New customer             4
4         1      New customer             5
5         1      New customer             6
6         1      New customer             7
7         1      New customer             8
8         1      New customer             9
9         1      New customer            10
10       15  Regular customer            15
11       15  Regular customer            17
12       15  Regular customer            18
13       15  Regular customer            21
14       15  Regular customer            22
15       19      New customer             2
16       19      New customer             5
17       19      New customer             7
18       21  Regular customer            10
19       31  Regular customer            10
20       31  Regular customer            17
21       43  Regular customer             6
22       43  Regular customer             9
23       52  Regular customer             1
24       52  Regular customer             2
25       52  Regular customer             3
26       52  Regular customer             5
27       52  Regular customer             7
28       52  Regular customer             9
29       52  Regular customer            10
30       52  Regular customer            11
31       52  Regular customer            12
32       52  Regular customer            15
33       52  Regular customer            17
34       52  Regular customer            18
35       52  Regular customer            19
36       52  Regular customer            21
37       67  Regular customer             1
38       67  Regular customer             2
39       67  Regular customer             3
40       67  Regular customer             4
41       67  Regular customer             5
42       67  Regular customer             6
43       67  Regular customer             8
44       67  Regular customer             9
45       67  Regular customer            10
46       67  Regular customer            11
47       67  Regular customer            12
48       67  Regular customer            13
49       67  Regular customer            14
50       67  Regular customer            16
51       67  Regular customer            18
52       67  Regular customer            19
53       67  Regular customer            21
54       67  Regular customer            22
55       67  Regular customer            23
56       81      New customer             3
57       81      New customer             5
58       82  Regular customer             1
59       82  Regular customer             3

In [18]:
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max']}).round(0)

                 prices
                   mean  min      max
loyalty_flag
Loyal customer     10.0  1.0  99999.0
New customer       13.0  1.0  99999.0
Regular customer   12.0  1.0  99999.0

### Creating Spender Flags

In [20]:
ords_prods_merge.loc[ords_prods_merge['prices'] >= 10, 'spender_type'] = 'High spender'

In [21]:
ords_prods_merge.loc[ords_prods_merge['prices'] < 10, 'spender_type'] = 'Low spender'

In [28]:
# Checking the Spender Type Column
ords_prods_merge['spender_type'].value_counts(dropna = False)

spender_type
Low spender     21760937
High spender    10643922
Name: count, dtype: int64

In [29]:
ords_prods_merge[['user_id', 'prices', 'loyalty_flag', 'spender_type']].head(100)

    user_id  prices      loyalty_flag spender_type
0         1     9.0      New customer  Low spender
1         1     9.0      New customer  Low spender
2         1     9.0      New customer  Low spender
3         1     9.0      New customer  Low spender
4         1     9.0      New customer  Low spender
5         1     9.0      New customer  Low spender
6         1     9.0      New customer  Low spender
7         1     9.0      New customer  Low spender
8         1     9.0      New customer  Low spender
9         1     9.0      New customer  Low spender
10       15     9.0  Regular customer  Low spender
11       15     9.0  Regular customer  Low spender
12       15     9.0  Regular customer  Low spender
13       15     9.0  Regular customer  Low spender
14       15     9.0  Regular customer  Low spender
15       19     9.0      New customer  Low spender
16       19     9.0      New customer  Low spender
17       19     9.0      New customer  Low spender
18       21     9.0  Regular customer  Low spender
19       31     9.0  Regular customer  Low spender
20       31     9.0  Regular customer  Low spender
21       43     9.0  Regular customer  Low spender
22       43     9.0  Regular customer  Low spender
23       52     9.0  Regular customer  Low spender
24       52     9.0  Regular customer  Low spender
25       52     9.0  Regular customer  Low spender
26       52     9.0  Regular customer  Low spender
27       52     9.0  Regular customer  Low spender
28       52     9.0  Regular customer  Low spender
29       52     9.0  Regular customer  Low spender
30       52     9.0  Regular customer  Low spender
31       52     9.0  Regular customer  Low spender
32       52     9.0  Regular customer  Low spender
33       52     9.0  Regular customer  Low spender
34       52     9.0  Regular customer  Low spender
35       52     9.0  Regular customer  Low spender
36       52     9.0  Regular customer  Low spender
37       67     9.0  Regular customer  Low spender
38       67     9.0  Regular customer  Low spender
39       67     9.0  Regular customer  Low spender
40       67     9.0  Regular customer  Low spender
41       67     9.0  Regular customer  Low spender
42       67     9.0  Regular customer  Low spender
43       67     9.0  Regular customer  Low spender
44       67     9.0  Regular customer  Low spender
45       67     9.0  Regular customer  Low spender
46       67     9.0  Regular customer  Low spender
47       67     9.0  Regular customer  Low spender
48       67     9.0  Regular customer  Low spender
49       67     9.0  Regular customer  Low spender
50       67     9.0  Regular customer  Low spender
51       67     9.0  Regular customer  Low spender
52       67     9.0  Regular customer  Low spender
53       67     9.0  Regular customer  Low spender
54       67     9.0  Regular customer  Low spender
55       67     9.0  Regular customer  Low spender
56       81     9.0      New customer  Low spender
57       81     9.0      New customer  Low spender
58       82     9.0  Regular customer  Low spender
59       82     9.0  Regular customer  Low spender
60       82     9.0  Regular customer  Low spender
61       82     9.0  Regular customer  Low spender
62       82     9.0  Regular customer  Low spender
63       82     9.0  Regular customer  Low spender
64       82     9.0  Regular customer  Low spender
65       82     9.0  Regular customer  Low spender
66       82     9.0  Regular customer  Low spender
67       98     9.0  Regular customer  Low spender
68       98     9.0  Regular customer  Low spender
69       98     9.0  Regular customer  Low spender
70       98     9.0  Regular customer  Low spender
71       98     9.0  Regular customer  Low spender
72       98     9.0  Regular customer  Low spender
73       98     9.0  Regular customer  Low spender
74      109     9.0      New customer  Low spender
75      120     9.0      New customer  Low spender
76      120     9.0      New customer  Low spender
77      185     9.0      New customer  Low spender
78      195     9.0    Loyal customer  Low spender
79      195     9.0    Loyal customer  Low spender
80      195     9.0    Loyal customer  Low spender
81      195     9.0    Loyal customer  Low spender
82      195     9.0    Loyal customer  Low spender
83      195     9.0    Loyal customer  Low spender
84      195     9.0    Loyal customer  Low spender
85      195     9.0    Loyal customer  Low spender
86      195     9.0    Loyal customer  Low spender
87      195     9.0    Loyal customer  Low spender
88      195     9.0    Loyal customer  Low spender
89      195     9.0    Loyal customer  Low spender
90      222     9.0    Loyal customer  Low spender
91      222     9.0    Loyal customer  Low spender
92      290     9.0    Loyal customer  Low spender
93      290     9.0    Loyal customer  Low spender
94      331     9.0      New customer  Low spender
95      360     9.0      New customer  Low spender
96      377     9.0      New customer  Low spender
97      387     9.0      New customer  Low spender
98      420     9.0  Regular customer  Low spender
99      420     9.0  Regular customer  Low spender

### Creating Order Frequency Flags

In [30]:
ords_prods_merge.loc[ords_prods_merge['days_since_prior_order'] > 20, 'order_frequency'] = 'Non-frequent customer'

In [31]:
ords_prods_merge.loc[(ords_prods_merge['days_since_prior_order'] > 10) & (ords_prods_merge['days_since_prior_order'] <= 20), 'order_frequency'] = 'Regular customer'

In [32]:
ords_prods_merge.loc[ords_prods_merge['days_since_prior_order'] <= 10, 'order_frequency'] = 'Frequent customer'

In [33]:
# Checking the Order Frequency column
ords_prods_merge['order_frequency'].value_counts(dropna = False)

order_frequency
Frequent customer        19042466
Regular customer          8131899
Non-frequent customer     5230494
Name: count, dtype: int64

In [34]:
ords_prods_merge[['user_id', 'prices', 'loyalty_flag', 'spender_type', 'order_frequency']].head(100)

    user_id  prices      loyalty_flag spender_type        order_frequency
0         1     9.0      New customer  Low spender       Regular customer
1         1     9.0      New customer  Low spender       Regular customer
2         1     9.0      New customer  Low spender  Non-frequent customer
3         1     9.0      New customer  Low spender  Non-frequent customer
4         1     9.0      New customer  Low spender  Non-frequent customer
5         1     9.0      New customer  Low spender       Regular customer
6         1     9.0      New customer  Low spender       Regular customer
7         1     9.0      New customer  Low spender       Regular customer
8         1     9.0      New customer  Low spender      Frequent customer
9         1     9.0      New customer  Low spender  Non-frequent customer
10       15     9.0  Regular customer  Low spender      Frequent customer
11       15     9.0  Regular customer  Low spender      Frequent customer
12       15     9.0  Regular customer  Low spender      Frequent customer
13       15     9.0  Regular customer  Low spender      Frequent customer
14       15     9.0  Regular customer  Low spender       Regular customer
15       19     9.0      New customer  Low spender      Frequent customer
16       19     9.0      New customer  Low spender      Frequent customer
17       19     9.0      New customer  Low spender      Frequent customer
18       21     9.0  Regular customer  Low spender      Frequent customer
19       31     9.0  Regular customer  Low spender      Frequent customer
20       31     9.0  Regular customer  Low spender      Frequent customer
21       43     9.0  Regular customer  Low spender      Frequent customer
22       43     9.0  Regular customer  Low spender      Frequent customer
23       52     9.0  Regular customer  Low spender       Regular customer
24       52     9.0  Regular customer  Low spender      Frequent customer
25       52     9.0  Regular customer  Low spender      Frequent customer
26       52     9.0  Regular customer  Low spender      Frequent customer
27       52     9.0  Regular customer  Low spender      Frequent customer
28       52     9.0  Regular customer  Low spender      Frequent customer
29       52     9.0  Regular customer  Low spender      Frequent customer
30       52     9.0  Regular customer  Low spender      Frequent customer
31       52     9.0  Regular customer  Low spender      Frequent customer
32       52     9.0  Regular customer  Low spender      Frequent customer
33       52     9.0  Regular customer  Low spender      Frequent customer
34       52     9.0  Regular customer  Low spender       Regular customer
35       52     9.0  Regular customer  Low spender      Frequent customer
36       52     9.0  Regular customer  Low spender  Non-frequent customer
37       67     9.0  Regular customer  Low spender       Regular customer
38       67     9.0  Regular customer  Low spender      Frequent customer
39       67     9.0  Regular customer  Low spender      Frequent customer
40       67     9.0  Regular customer  Low spender      Frequent customer
41       67     9.0  Regular customer  Low spender      Frequent customer
42       67     9.0  Regular customer  Low spender      Frequent customer
43       67     9.0  Regular customer  Low spender      Frequent customer
44       67     9.0  Regular customer  Low spender      Frequent customer
45       67     9.0  Regular customer  Low spender      Frequent customer
46       67     9.0  Regular customer  Low spender      Frequent customer
47       67     9.0  Regular customer  Low spender      Frequent customer
48       67     9.0  Regular customer  Low spender      Frequent customer
49       67     9.0  Regular customer  Low spender      Frequent customer
50       67     9.0  Regular customer  Low spender      Frequent customer
51       67     9.0  Regular customer  Low spender      Frequent customer
52       67     9.0  Regular customer  Low spender      Frequent customer
53       67     9.0  Regular customer  Low spender      Frequent customer
54       67     9.0  Regular customer  Low spender       Regular customer
55       67     9.0  Regular customer  Low spender       Regular customer
56       81     9.0      New customer  Low spender       Regular customer
57       81     9.0      New customer  Low spender  Non-frequent customer
58       82     9.0  Regular customer  Low spender       Regular customer
59       82     9.0  Regular customer  Low spender      Frequent customer
60       82     9.0  Regular customer  Low spender       Regular customer
61       82     9.0  Regular customer  Low spender       Regular customer
62       82     9.0  Regular customer  Low spender  Non-frequent customer
63       82     9.0  Regular customer  Low spender      Frequent customer
64       82     9.0  Regular customer  Low spender       Regular customer
65       82     9.0  Regular customer  Low spender      Frequent customer
66       82     9.0  Regular customer  Low spender      Frequent customer
67       98     9.0  Regular customer  Low spender  Non-frequent customer
68       98     9.0  Regular customer  Low spender      Frequent customer
69       98     9.0  Regular customer  Low spender  Non-frequent customer
70       98     9.0  Regular customer  Low spender       Regular customer
71       98     9.0  Regular customer  Low spender  Non-frequent customer
72       98     9.0  Regular customer  Low spender  Non-frequent customer
73       98     9.0  Regular customer  Low spender      Frequent customer
74      109     9.0      New customer  Low spender      Frequent customer
75      120     9.0      New customer  Low spender       Regular customer
76      120     9.0      New customer  Low spender       Regular customer
77      185     9.0      New customer  Low spender  Non-frequent customer
78      195     9.0    Loyal customer  Low spender       Regular customer
79      195     9.0    Loyal customer  Low spender      Frequent customer
80      195     9.0    Loyal customer  Low spender      Frequent customer
81      195     9.0    Loyal customer  Low spender      Frequent customer
82      195     9.0    Loyal customer  Low spender      Frequent customer
83      195     9.0    Loyal customer  Low spender      Frequent customer
84      195     9.0    Loyal customer  Low spender      Frequent customer
85      195     9.0    Loyal customer  Low spender      Frequent customer
86      195     9.0    Loyal customer  Low spender      Frequent customer
87      195     9.0    Loyal customer  Low spender      Frequent customer
88      195     9.0    Loyal customer  Low spender      Frequent customer
89      195     9.0    Loyal customer  Low spender      Frequent customer
90      222     9.0    Loyal customer  Low spender      Frequent customer
91      222     9.0    Loyal customer  Low spender      Frequent customer
92      290     9.0    Loyal customer  Low spender      Frequent customer
93      290     9.0    Loyal customer  Low spender      Frequent customer
94      331     9.0      New customer  Low spender  Non-frequent customer
95      360     9.0      New customer  Low spender       Regular customer
96      377     9.0      New customer  Low spender      Frequent customer
97      387     9.0      New customer  Low spender  Non-frequent customer
98      420     9.0  Regular customer  Low spender  Non-frequent customer
99      420     9.0  Regular customer  Low spender       Regular customer

In [35]:
# Export Data as Pickle
ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products_agg.pkl'))